#!/bin/bash
BG_CMD=$HOME/.fehbg

border_Active=#282828
border_Bg=#161616
border_Outer=#282828

gtk_theme=Materia-dark-compact
icon_theme=Papirus-Dark
cursor_size=16
cursor_theme=Plasma-Overdose
font_name="IBM Plex Sans"

