#!/bin/bash

gnome_schema="org.gnome.desktop.interface"
pgrep -x gsd-xsettings || /usr/libexec/gsd-xsettings &
pgrep -x dunst || /usr/bin/dunst &
pgrep -x picom || /usr/bin/picom &
pgrep -x eww || eww open bar &
pgrep -x unclutter || unclutter -idle 5 &

source ~/.config/herbstluftwm/conf
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" cursor-size "$cursor_size"
gsettings set "$gnome_schema" font-name "$font_name"

echo "Xcursor.size: ${cursor_size}
Xcursor.theme: ${cursor_theme}" > ~/.Xresources
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

