[build]
rustc-wrapper = "sccache" 

[target.x86_64-unknown-linux-gnu]
linker = "clang-17"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]


[profile.dev]
debug = false

[profile.release]
lto = true
codegen-units = 1

[registries.crates-io]
protocol = "sparse"

