#!/usr/bin/bash

export wm_name="i3"
export gtk_theme="rose-pine-gtk"
#export gtk_theme="Orchis-Dark-Compact"
export gtk_icon="Papirus-Dark"
export font="Cantarell"
export cursor="macOS-BigSur"
export cursor_size=24
